#
# Makefile for the drivers of Marvell devices.
#
obj-$(CONFIG_MRVL_MMP_MODEM)   += marvell-telephony/
obj-$(CONFIG_MRVL_TZDD)   += security/mmp-tzdd/src/
obj-$(CONFIG_MRVL_GEU)   += security/mmp-geu/
obj-$(CONFIG_MRVL_SD8XXX)	+= sd8787/
obj-$(CONFIG_MARVELL_DRIVERS)	+= mpdc/

obj-$(CONFIG_MRVL_GPU_GALCORE)   += graphics/galcore_4x/
